name: Todoist Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every 5 minute
    - cron: "*/5 * * * *"

jobs:
  update-readme:
    name: Update todoist stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: unixfy/todoist-readme@master
        with:
          TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
          PREMIUM: true
